#version: 2

project_name: erigon

release:
  disable: true
  draft: true
  prerelease: auto

env:
  - CGO_ENABLED=1
  - BUILD_VERSION={{ .Env.BUILD_VERSION }}
  - DARWIN_LDFLAGS="-O3 -g -mmacosx-version-min=13.3"
  - CGO_CFLAGS_DEFAULT=-DMDBX_ENV_CHECKPID=0 -DMDBX_DISABLE_VALIDATION=0 -DMDBX_FORCE_ASSERTIONS=0 -Wno-unknown-warning-option -Wno-enum-int-mismatch -Wno-strict-prototypes -Wno-unused-but-set-variable -O3
  - CGO_LDFLAGS_DEFAULT=-O3 -g
  - GOPRIVATE_DEFAULT=github.com/erigontech/silkworm-go

builds:


## Linux AMD64:
  - id: linux-amd64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    goamd64:
      - v2
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-amd64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ linux ]
    goarch: [ amd64 ]
    goamd64:
      - v2
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-amd64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ linux ]
    goarch: [ amd64 ]
    goamd64:
      - v2
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-amd64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ linux ]
    goarch: [ amd64 ]
    goamd64:
      - v2
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-amd64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ linux ]
    goarch: [ amd64 ]
    goamd64:
      - v2
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

## End of Linux AMD64.

## Linux ARM64
  - id: linux-arm64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }} -D__BLST_PORTABLE__
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-arm64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }} -D__BLST_PORTABLE__
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-arm64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }} -D__BLST_PORTABLE__
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-arm64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }} -D__BLST_PORTABLE__
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

  - id: linux-arm64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS={{ .Env.CGO_CFLAGS_DEFAULT }} -D__BLST_PORTABLE__
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS_DEFAULT }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}

## End of Linux ARM64.


checksum:
  name_template: "{{ .Env.APPLICATION }}_{{ .Env.BUILD_VERSION }}_checksums.txt"
  algorithm: sha256
  ids:
    - linux-arm64
    - linux-amd64


archives:
  - id: linux-arm64
    builds:
      - linux-arm64-erigon
      - linux-arm64-downloader
      - linux-arm64-devnet
      - linux-arm64-evm
      - linux-arm64-caplin
    name_template: "{{ .Env.APPLICATION }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz

  - id: linux-amd64
    builds:
      - linux-amd64-erigon
      - linux-amd64-downloader
      - linux-amd64-devnet
      - linux-amd64-evm
      - linux-amd64-caplin
    name_template: "{{ .Env.APPLICATION }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz

