#version: 2

project_name: erigon

release:
  disable: true
  draft: true
  prerelease: auto

env:
  - CGO_ENABLED=1
  - BUILD_VERSION={{ .Env.BUILD_VERSION }}
  - GIT_COMMIT={{ .Env.GIT_COMMIT }}
  - GIT_BRANCH={{ .Env.GIT_BRANCH }}
  - GIT_TAG={{ .Env.GIT_TAG }}
  - DARWIN_LDFLAGS="-O3 -g -mmacosx-version-min=13.3"
  - PACKAGE={{ .Env.PACKAGE }}
  - GO_FLAGS=-trimpath -buildvcs=false -ldflags "-X {{ .Env.PACKAGE }}/params.GitCommit={{ .Env.GIT_COMMIT }} -X {{ .Env.PACKAGE }}/params.GitBranch={{ .Env.GIT_BRANCH }} -X {{ .Env.PACKAGE }}/params.GitTag={{ .Env.GIT_TAG }}"

builds:

## Darwin AMD64:
  - id: darwin-amd64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ amd64 ]
    skip: {{ .Env.SKIP_DARWIN_AMD64 }}
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-amd64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ darwin ]
    goarch: [ amd64 ]
    skip: {{ .Env.SKIP_DARWIN_AMD64 }}
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-amd64-devnet
    main: ./cmd/devnet
    binary: devenet
    goos: [ darwin ]
    goarch: [ amd64 ]
    skip: {{ .Env.SKIP_DARWIN_AMD64 }}
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-amd64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ darwin ]
    goarch: [ amd64 ]
    skip: {{ .Env.SKIP_DARWIN_AMD64 }}
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-amd64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ darwin ]
    goarch: [ amd64 ]
    skip: {{ .Env.SKIP_DARWIN_AMD64 }}
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

## END of Darwin AMD64.

## Darwin ARM64:
  - id: darwin-arm64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ arm64 ]
    skip: {{ .Env.SKIP_DARWIN_ARM64 }}
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-arm64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ darwin ]
    goarch: [ arm64 ]
    skip: {{ .Env.SKIP_DARWIN_ARM64 }}
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-arm64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ darwin ]
    goarch: [ arm64 ]
    skip: {{ .Env.SKIP_DARWIN_ARM64 }}
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-arm64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ darwin ]
    goarch: [ arm64 ]
    skip: {{ .Env.SKIP_DARWIN_ARM64 }}
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: darwin-arm64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ darwin ]
    goarch: [ arm64 ]
    skip: {{ .Env.SKIP_DARWIN_ARM64 }}
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS={{ .Env.DARWIN_LDFLAGS }}
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w
## END of Darwin ARM64.

## Linux AMD64:
  - id: linux-amd64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-amd64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-amd64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-amd64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-amd64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

## End of Linux AMD64.

## Linux ARM64
  - id: linux-arm64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

## End of Linux ARM64.

## Windows AMD64
  - id: windows-amd64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: windows-amd64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: windows-amd64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: windows-amd64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

  - id: windows-amd64-caplin
    main: ./cmd/caplin
    binary: caplin
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - GO_FLAGS={{ .Env.GO_FLAGS }}
    tags: [ nosqlite, noboltdb, nosilkworm ]
    ldflags: -s -w

## End of Windows AMD64

archives:
  - id: darwin-amd64
    builds:
      - darwin-amd64-erigon
      - darwin-amd64-downloader
      - darwin-amd64-devnet
      - darwin-amd64-evm
      - darwin-amd64-caplin
    name_template: "{{ .ProjectName }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: {{ if eq .Env.SKIP_DARWIN_AMD64 "true" }}binary{{ else }}tar.gz{{ end }}

  
  - id: darwin-arm64
    builds:
      - darwin-arm64-erigon
      - darwin-arm64-downloader
      - darwin-arm64-devnet
      - darwin-arm64-evm
      - darwin-arm64-caplin
    name_template: "{{ .ProjectName }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: {{ if eq .Env.SKIP_DARWIN_ARM64 "true" }}binary{{ else }}tar.gz{{ end }}

  - id: linux-arm64
    builds:
      - linux-arm64-erigon
      - linux-arm64-downloader
      - linux-arm64-devnet
      - linux-arm64-evm
      - linux-arm64-caplin
    name_template: "{{ .ProjectName }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz

  - id: linux-amd64
    builds:
      - linux-amd64-erigon
      - linux-amd64-downloader
      - linux-amd64-devnet
      - linux-amd64-evm
      - linux-amd64-caplin
    name_template: "{{ .ProjectName }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz

  - id: windows-amd64
    builds:
      - windows-amd64-erigon
      - windows-amd64-downloader
      - windows-amd64-devnet
      - windows-amd64-evm
      - windows-amd64-caplin
    name_template: "{{ .ProjectName }}_{{ .Env.BUILD_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip


dockers:
  - dockerfile: Dockerfile.NEW-gr
    use: buildx
    goarch: amd64
    goos: linux
    ids:
      - linux-amd64-erigon
      - linux-amd64-downloader
      - linux-amd64-devnet
      - linux-amd64-evm
      - linux-amd64-caplin
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Env.LABEL_DESCRIPTION }}
      - --label=org.opencontainers.image.url={{ .Env.PACKAGE }}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.vcs-ref={{ .Env.GIT_COMMIT }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .Env.GIT_COMMIT }}
      - "--build-arg=TARGET_BASE_VERSION={{.Env.TARGET_BASE_VERSION}}"
    image_templates:
      - '{{ .Env.DOCKER_URL }}:{{ .Env.BUILD_VERSION }}'
  - dockerfile: Dockerfile.NEW-gr
    use: buildx
    goarch: arm64
    goos: linux
    ids:
      - linux-arm64-erigon
      - linux-arm64-downloader
      - linux-arm64-devnet
      - linux-arm64-evm
      - linux-arm64-caplin
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Env.LABEL_DESCRIPTION }}
      - --label=org.opencontainers.image.url={{ .Env.PACKAGE }}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.vcs-ref={{ .Env.GIT_COMMIT }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .Env.GIT_COMMIT }}
      - "--build-arg=TARGET_BASE_VERSION={{.Env.TARGET_BASE_VERSION}}"
    image_templates:
      - '{{ .Env.DOCKER_URL }}:{{ .Env.BUILD_VERSION }}'

docker_manifests:
  - name_template: "{{ .Env.DOCKER_IMAGE }}:{{ .Env.BUILD_VERSION }}"
    image_templates:
      - "{{ .Env.DOCKER_URL }}:{{ .Env.BUILD_VERSION }}"
      - "{{ .Env.DOCKER_URL }}:{{ .Env.BUILD_VERSION }}"