name: Release2

env:
  DOCKER_REG_ADDRESS: "this"
  DOCKER_REG_USERNAME: "user"
  DOCKER_REG_PASSWORD: "password"

on:
  push:
    branches-ignore:
      - '**'
    tags:
      ## only trigger on release tags:
      #- 'v*.*.*'
      #- 'v*.*.*-*'
  workflow_dispatch:

jobs:
  build-and-deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Available diskspace before checkout
        run: df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Debug output
        run: |
          echo ${{ github.event }}
          echo ${{ steps.prepare }}
          echo "Debug SET output"
          set
          docker images