name: Release

# Uncomment the following to let goreleaser automatically
# create a GitHub release when a tag is pushed.
# permissions:
#   contents: write

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: dockerhub-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: ghcr-login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - run: echo ${{ steps.prepare.outputs.tag_name }}

      - name: Run GoReleaser
        run: |
          echo "DEBUG : Checking make version"
          make --version
          echo "-- end --"
          echo "DEBUG : checking content of current directory"
          ls -lao .
          echo "-- end --"
          echo "DEBUG : checking docker daemon configuration"
          cat /etc/docker/daemon.json
          echo "-- end --"
          echo "DEBUG : run make release-dry-run"
          make release-dry-run
          echo "-- end --"
          echo "DEBUG : print recursive list of files"
          find ./dist -type f -ls
          echo "-- end --"
          echo "DEBUG : print list of local docker images"
          docker images
          echo "-- end --"
          echo "DEBUG : docker image amd64"
          docker image inspect thorax/erigon:2.59.1-amd64 || true
          echo "-- end --"
          echo "DEBUG : docker image arm64"
          docker image inspect thorax/erigon:2.59.1-arm64 || true
          echo "-- end --"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_KEY }}